### PR TITLE
added alternative parts

### LINKED ISSUE #32: Fix microusb part name with proper attributes.
Currently it's wrong.

### LINKED ISSUE #33: Change FET
Current one is obsolete, change the attribute

### LINKED ISSUE #35: Update schematic & BOM with alternative parts

### PR DESCRIPTION
**Pull request by Zentrus**
schematic update
README update

also repacked the manufacturing docs

### CODE REVIEW

**Comment by Zentrus** [comment]
[Komar.manufacturing.doc.zip](https://github.com/Zubax/Komar/files/9992578/Komar.manufacturing.doc.zip)
here's the new release - please review if it's correct.

**Comment by Zentrus** [comment]
oh before merging. I think I can do the other pending issues as well - change FET & updating the micro USB attributes. I just need to know what to write there. #32

**Review by suzonch — APPROVED** [review]

**Review by suzonch — APPROVED** [review]

**Comment by suzonch** [comment]
Please link issues with commits

**Review by pavel-kirienko — CHANGES_REQUESTED** [review]
The FET update is not reflected in the changelog.

**Comment by suzonch** [comment]
> The FET update is not reflected in the changelog.

It's added as alternative 
image

**Comment by pavel-kirienko** [comment]
Okay. Can we please make it clearer which parts were updated? An extra column in the table added to the README indicating the function of each component (e.g., FET, USB connector, etc.) would help.

**Review by pavel-kirienko — APPROVED** [review]

**Pull request merged**
