### PR TITLE
changed usb back to through-hole

### LINKED ISSUE #26: Replace the current USB connector with a more robust alternative
See feedback from Katla Aero forwarded by Dmitry today.

### PR DESCRIPTION
**Pull request by suzonch**
fixes #26

### CODE REVIEW

**Review by pavel-kirienko — APPROVED** [review]

**Review by pavel-kirienko — APPROVED** [review]
@farzan-saleem waiting for you here

**Review by farzan-saleem — APPROVED** [review]

**Review by farzan-saleem — CHANGES_REQUESTED** [review]
Please make sure there is no clash between components. If you cant move diode then you need to edit the footprint.

image

Old design

image

**Review by pavel-kirienko — APPROVED** [review]

**Review by farzan-saleem — CHANGES_REQUESTED** [review]
Power vias are not connected properly.
image


Old design for reference.
image

**Review by farzan-saleem — CHANGES_REQUESTED** [review]
You have reduced power trace to 9mil. It need to be at least 15mil.
image

**Review by farzan-saleem — APPROVED** [review]

**Pull request merged**
